### ISSUE TITLE
Is there a way to have open parallel session with this lib and browser?

### ISSUE THREAD

**Issue by Algoeye1** [jugaad-py/jugaad-trader#10]
When i login using this lib and try to login in browser the others log out . Is there a way to have the parallel session open in browser?

**Comment by priyalorha** [comment]
you can store the session key and then connect. I have a entirely new api that connects and places trade, u might like to check and see how to save the session key and reuse it

**Comment by Algoeye1** [comment]
Sorted , Thanks

**Comment by Algoeye1** [comment]
> you can store the session key and then connect. I have a entirely new api that connects and places trade, u might like to check and see how to save the session key and reuse it

Can you share your API?

**Comment by sevakram** [comment]
> When i login using this lib and try to login in browser the others log out . Is there a way to have the parallel session open in browser?

In order to do it, you'll have to login to your account in your browser and capture the `enctoken` from request headers and use it in your code. So for Zerodha both connections are from same client and as long as token does not expire (i guess for 24 hours), both python and browser session will run simultaneously.

Step 1
<img width="399" alt="Capture" src="https://user-images.githubusercontent.com/69081175/114178600-95d88200-995b-11eb-939a-8d6b0ee8aab2.PNG">
Copy the enctoken from the headers

Steps 2
Plug enctoken  in the code in place of ENC_TOKEN_FROM_DEV_TOOLS (string starting Mok***)

```python
from jugaad_trader import Zerodha
kite = Zerodha()
kite.enc_token = "ENC_TOKEN_FROM_DEV_TOOLS"
profile = kite.full_profile()
print(profile)
```

Hope this helps.

**Comment by Algoeye1** [comment]
Yes , Many thanks!
