### ISSUE TITLE
Error placing multiple orders Zerodha

### ISSUE THREAD

**Issue by iamknownstranger** [jugaad-py/jugaad-trader#16]
HTTPSConnectionPool(host='kite.zerodha.com', port=443): Max retries exceeded with url: /oms/quote/ltp?i=9957378 (Caused by SSLError(SSLError("read error: Error([('SSL routines', 'ssl3_get_record', 'decryption failed or bad record mac')])")))

I'm using multithreading to place errors this error is being raised despite multiple exceptions handling.

**Comment by cmullu** [comment]
Error raised with kite.ltp()

**Comment by priyalorha** [comment]
More than an error, it could be because of the service being not available.

**Comment by sevakram** [comment]
I read through the stack overflow answers, i think it is related to network issue or service availablity as @priyalorha mentioned.

Even though the error says SSLError, it might have caused because it could not decrypt completely as connectivity terminated.

Next steps-
1. To eliminate network issue try running it in a VM in cloud such as GCP/aws/digital ocean. There connectivity will not be an issue
2. If it still persists, then one possibility is that Zerodha is throttling your requests, the api we use for jugaad is meant for browser, and browsers do not fetch data in multiple threads at high rates. So solution might be to reduce the rate at which you are sending requests or if you have mastered your algorithm and earning a good amount, consider switching to official API

Do let us know whqt was the issue

**Comment by sevakram** [comment]
[Refer this discussion on official Kite API](https://kite.trade/forum/discussion/257/api-rate-limiting)

/instruments (market quote call) - max 60 requests per minute
/instruments/historical - max 120 requests per minute (2 requests/sec)

**Comment by sevakram** [comment]
Closing the issue for now, please reopen in case you face same issue
