### ISSUE TITLE
[Enhancement] Need Bracket order functionality

### ISSUE THREAD

**Issue by dipankardevops** [jugaad-py/jugaad-trader#19]
Hi,

Zerodha many time blocks bracket orders due to high volatility for both cash market and FNO. Can we have some kind of feature where we place order with a predefined target and stoploss ? 
This feature would also do magic in scalping.
P.S. Zerodha has blocked placing BO for FNO catagory.

**Comment by sevakram** [comment]
If I understand correctly, you are looking for an alternate implementation of bracket order so that you are not dependent on Zerodha blocking/unblocking the default bracket order functionality.

So to answer, can it be done? Yes
Will the feature be part of jugaad - No, this library will only be a simple wrapper over kiteconnect, providing the same functionality which you get thru API or browser. Any additional logic needs to be developed by end user.
