### ISSUE TITLE
Basket order

### ISSUE THREAD

**Issue by bibinvargheset** [jugaad-py/jugaad-trader#29]
Can you implement https://kite.trade/docs/connect/v3/basket/ , this will reduce the margin required in options.

**Comment by sevakram** [comment]
Hi Bibin,

The method provided in link is not part of Kite API. There is not support for basket order in official Kite API as far as I can see.

It is part of Kite publisher API, in which you can include some HTML and JS code in your website and visitors can click the button on your website and get redirected to Zerodha for execution.

eg. If you are providing stock recommendation in your blog, you can provide a buy/sell button their so that visitors can take action from your blog itself.

Advise you to open an issue on their github repo https://github.com/zerodha/pykiteconnect as a basket order feature request.

Once they provide this feature `jugaad-trader` will automatically inherit that feature.

**Comment by bibinvargheset** [comment]
Its mentioned implemented  no documentation available 
https://github.com/zerodha/pykiteconnect/issues/115
